language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - wget https://github.com/OSGeo/proj.4/releases/download/5.0.1/proj-5.0.1.tar.gz
  - tar -xzvf proj-5.0.1.tar.gz
  - pushd proj-5.0.1 && ./configure --prefix=/usr && make && sudo make install && popd
  
