[package]
name = "proj-sys"
description = "Rust bindings for proj.4 v5.0"
version = "0.1.0"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
keywords = ["proj", "projection", "osgeo", "geo"]
license = "MIT/Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.33.1"
