[package]
name = "proj-sys"
description = "Rust bindings for proj.4 v5.0.x"
repository = "https://github.com/urschrei/proj-sys"
version = "0.2.0"
readme = "README.md"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
keywords = ["proj", "projection", "osgeo", "geo", "geospatial"]
license = "MIT/Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.33.1"
