[package]
name = "proj-sys"
description = "Rust bindings for PROJ v6.3.x"
repository = "https://github.com/urschrei/proj-sys"
version = "0.12.1"
readme = "README.md"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
keywords = ["proj", "projection", "osgeo", "geo", "geospatial"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.52.0"

[features]
nobuild = []

[package.metadata.docs.rs]
features = [ "nobuild" ] # This feature will be enabled during the docs.rs build
